In [12]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/udmy/Nba Teams(1).xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

//Guarda en nba la ingomacion del excel y muestra las 5 primeras filas

In [15]:
nba["Name"]

0      Bogdan Bogdanovic
1        Brandon Goodwin
2         Bruno Fernando
3            Cam Reddish
4           Clint Capela
             ...
493        Rui Hachimura
494                  NaN
495    Russell Westbrook
496        Thomas Bryant
497       Troy Brown Jr.
Name: Name, Length: 498, dtype: object

//Muestra la columna de llamada name

In [16]:
nba["Salary"]

0      18000000.0
1       1701593.0
2       1517981.0
3             NaN
4      16000000.0
          ...
493     4692840.0
494           NaN
495    41358814.0
496     8333333.0
497     3372840.0
Name: Salary, Length: 498, dtype: float64

muestra la columna salary

In [17]:
nba.Name

0      Bogdan Bogdanovic
1        Brandon Goodwin
2         Bruno Fernando
3            Cam Reddish
4           Clint Capela
             ...
493        Rui Hachimura
494                  NaN
495    Russell Westbrook
496        Thomas Bryant
497       Troy Brown Jr.
Name: Name, Length: 498, dtype: object

//Muestra la columna name